In [2]:
import numpy as np

In [10]:
np.random.randn(2,4)

array([[ 1.02420072,  0.87642371, -0.02001582,  0.16565001],
       [-0.35900174,  0.72410955,  0.92851154, -0.22602634]])

In [17]:
np.random.rand(2,4)

array([[ 0.62426945,  0.01012737,  0.86823801,  0.00549771],
       [ 0.97288113,  0.87598164,  0.17538168,  0.11190809]])

In [4]:
a/b

array([[ 0.60832874,  1.91637354,  0.76237086],
       [ 0.83232489,  2.27604217,  1.00943274],
       [ 0.30678617,  1.96063365,  0.71772391],
       [ 0.68034005,  0.03922543,  1.09640275]])

In [5]:
a = np.sum(a, axis=1)

In [6]:
abs(a)

array([ 1.75089323,  2.25057825,  1.50015551,  1.45620411])

In [8]:
np.sum(a)

6.957831101827967

In [3]:
A = np.random.randn(4,3)
B = np.sum(A, axis = 1, keepdims = True)

In [4]:
B.shape

(4, 1)